### ISSUE TITLE
Documentation for an Admin to grant a User access

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#103]

**Comment by ahulab** [comment]
https://docs.google.com/document/d/15c0pxAXmvbVONEbRPaNv08JtKTbYIxC3oKHE3WsUzNA/edit?usp=sharing

**Comment by evandana** [comment]
Looks great!!

**Comment by pandathegiant** [comment]
This is great indeed!

Now I will suggest minor tweaks:
- Once the back-end schema initialization PR is merged, the "Administrator" role, as opposed to "Admin" role should be used.
- Or better, use "Editor" role, since now the Admin is really allowed to read/update/create records, and we might need a real "Administrator" role for real administrative permission in the future.
- Also, we can document the "Viewer" role to allow some users to only view but not write records.  This however needs further testing.

**Comment by pandathegiant** [comment]
@ahulab It doesn't seem that I have permission to change the Google doc above; so I can only make suggestions above.

**Comment by evandana** [comment]
Resolved
https://github.com/evandana/keep-ahope/wiki/Authorizing-a-User
